### ISSUE TITLE
Match query doesn't properly handle LocalDate

### ISSUE THREAD

**Issue by BFergerson** [vaticle/typedb#4648]
Given the schema:
```
define
day sub attribute datatype date;
```

The following code works:
```java
Grakn.Transaction writeTx = session.transaction(GraknTxType.WRITE);
writeTx.graql().insert(var("d").isa("day").val(LocalDate.now())).execute();
```

While the following code:
```java
Grakn.Transaction writeTx = session.transaction(GraknTxType.WRITE);
writeTx.graql().match(var("d").isa("day").val(LocalDate.now())).get().execute();
```

Throws this error:
```
Exception in thread "main" ai.grakn.exception.GraqlQueryException: unsupported attribute value type class java.time.LocalDate
	at ai.grakn.exception.GraqlQueryException.invalidValueClass(GraqlQueryException.java:245)
	at ai.grakn.graql.internal.query.predicate.ComparatorPredicate.lambda$persistedValue$1(ComparatorPredicate.java:89)
	at java.util.Optional.map(Optional.java:215)
	at ai.grakn.graql.internal.query.predicate.ComparatorPredicate.persistedValue(ComparatorPredicate.java:83)
	at ai.grakn.graql.internal.query.predicate.ComparatorPredicate.hashCode(ComparatorPredicate.java:135)
	at ai.grakn.graql.internal.query.predicate.EqPredicate.hashCode(EqPredicate.java:75)
	at ai.grakn.graql.internal.pattern.property.AutoValue_ValueProperty.hashCode(AutoValue_ValueProperty.java:41)
	at java.util.AbstractSet.hashCode(AbstractSet.java:126)
	at ai.grakn.graql.internal.pattern.VarPatternImpl.hashCode(VarPatternImpl.java:72)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.put(HashMap.java:612)
	at java.util.HashSet.add(HashSet.java:220)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at java.util.HashSet.<init>(HashSet.java:120)
	at com.google.common.collect.Sets.newHashSet(Sets.java:276)
	at ai.grakn.graql.internal.query.QueryBuilderImpl.match(QueryBuilderImpl.java:96)
	at ai.grakn.graql.internal.query.QueryBuilderImpl.match(QueryBuilderImpl.java:87)
```

**Comment by richard-julien** [comment]
It seems grakn doesn't support timezone, so not compliant with ISO 8601. If i tried to absorb 1977-04-22T06:00:00Z it fail, but 1977-04-22T06:00:00 succeed.
