### ISSUE TITLE
Flaky test: ReasoningIT::whenAppendingRolePlayers_queryIsRewrittenCorrectly

### ISSUE THREAD

**Issue by kasper-piskorski** [vaticle/typedb#5502]
`whenAppendingRolePlayers_queryIsRewrittenCorrectly` fails randomly.

```
There was 1 failure:

1) whenAppendingRolePlayers_queryIsRewrittenCorrectly(grakn.core.graql.reasoner.ReasoningIT)

java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at grakn.core.graql.reasoner.ReasoningIT.whenAppendingRolePlayers_queryIsRewrittenCorrectly(ReasoningIT.java:584)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
```

**Comment by flyingsilverfin** [comment]
Fixed with #5638

**Comment by jmsfltchr** [comment]
Still seeing this issue, so we determine that it isn't fixed in fact.

**Comment by krishnangovindraj** [comment]
The test has since been replaced and we no longer see flaky tests in reasoner.
