### ISSUE TITLE
Grakn has batch size limits?

### ISSUE THREAD

**Issue by BFergerson** [vaticle/typedb#5563]
## Description

I'm running a query that used to insert 100,000 things into Grakn 1.5 and it is failing now because of a batch size limit in Grakn 1.6. I have no issue with the batch size limit but I could not find any documentation on it.

I figured I would also use this issue to suggest that exceptions that are thrown in the backend of Grakn also be sent to the client. So far every exception I've gotten on the Java Graql client says something like:
```
Exception in thread "main" grakn.client.exception.GraknClientException: UNKNOWN: Could not commit transaction due to exception during persistence. Please check server logs for the stack trace.
	at grakn.client.exception.GraknClientException.create(GraknClientException.java:49)
	at grakn.client.GraknClient$Transaction.responseOrThrow(GraknClient.java:528)
	at grakn.client.GraknClient$Transaction.commit(GraknClient.java:539)
	at grakn.client.GraknClient$Transaction$commit$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at GraknCalendarTest.main(GraknCalendarTest.groovy:57)
```

Whereas the server says:
```
2020-01-27 08:54:47,436 [transaction-listener] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
grakn.core.graph.core.JanusGraphException: Could not commit transaction due to exception during persistence
	at grakn.core.graph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1327)
	at grakn.core.server.session.TransactionImpl.persistInternal(TransactionImpl.java:235)
	at grakn.core.server.session.TransactionImpl.commitInternal(TransactionImpl.java:223)
	at grakn.core.server.session.TransactionImpl.commit(TransactionImpl.java:1141)
	at grakn.core.server.rpc.SessionService$TransactionListener.commit(SessionService.java:331)
	at grakn.core.server.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:226)
	at grakn.core.server.rpc.SessionService$TransactionListener.lambda$onNext$1(SessionService.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: grakn.core.graph.core.JanusGraphException: Exception while executing backend operation CacheMutation
	at grakn.core.graph.diskstorage.util.BackendOperation.execute(BackendOperation.java:66)
	at grakn.core.graph.diskstorage.keycolumnvalue.cache.CacheTransaction.persist(CacheTransaction.java:97)
	at grakn.core.graph.diskstorage.keycolumnvalue.cache.CacheTransaction.flushInternal(CacheTransaction.java:139)
	at grakn.core.graph.diskstorage.keycolumnvalue.cache.CacheTransaction.commit(CacheTransaction.java:200)
	at grakn.core.graph.diskstorage.BackendTransaction.commitStorage(BackendTransaction.java:120)
	at grakn.core.graph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:644)
	at grakn.core.graph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1317)
	... 11 common frames omitted
Caused by: java.lang.IllegalStateException: Batch statement cannot contain more than 65535 statements.
	at com.datastax.oss.driver.internal.core.cql.DefaultBatchStatement.addAll(DefaultBatchStatement.java:186)
	at grakn.core.graph.diskstorage.cql.CQLStoreManager.mutateManyUnlogged(CQLStoreManager.java:464)
	at grakn.core.graph.diskstorage.cql.CQLStoreManager.mutateMany(CQLStoreManager.java:391)
	at grakn.core.graph.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:100)
	at grakn.core.graph.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:97)
	at grakn.core.graph.diskstorage.util.BackendOperation.execute(BackendOperation.java:53)
	... 17 common frames omitted
```

If possible, I think it would be more beneficial if these exceptions are thrown by the client. I often use Grakn behind Docker so there are extra steps to get to these exceptions. I'm just arguing that it would be more simple if the client said why the server failed rather than just saying the server failed. I'm not saying the client needs to be as verbose or more verbose than the server. Just that the client could give some indication (general error codes for example).

## Environment

1. OS (where Grakn server runs): Ubuntu 18.04
2. Grakn version (and platform): Grakn Core 1.6.2
3. Grakn client: client-java

## Reproducible Steps

Try to insert 100,000 things into Grakn in one transaction

## Additional information

Feel free to close this issue whenever. I just wanted to suggest that there should be something that talks about the size limits for batching and that it would be beneficial if the client could give better error descriptions than to check the server.

**Comment by flyingsilverfin** [comment]
Good catch @BFergerson , our error messages in general can be improved!

**Comment by flyingsilverfin** [comment]
N/A in 2.0 as no longer using Cassandra.
Note that inserting that many things will probably still not be a particularly fast process!
