### ISSUE TITLE
Grakn crashes, Java heap space

### ISSUE THREAD

**Issue by SamuelHassine** [vaticle/typedb#5683]
## Description

One of our customer's production instance crashes this night with the following errors:

```
Apr 10 15:14:57 lab-prod-opencti OpenCTI-Server[23712]: message repeated 2 times: [ error: [GRAKN] executeRead error > 2 UNKNOWN: Java heap space. Please check server logs for the stack trace. {"code":2,"metadata":{"_internal_repr":{},"flags":0},"details":"Java heap space. Please check server logs for the stack trace.","stack":"Error: 2 UNKNOWN: Java heap space. Please check server logs for the stack trace.\n    at Object.exports.createStatusError (/opt/opencti/node_modules/grpc/src/common.js:91:15)\n    at ClientDuplexStream._emitStatusIfDone (/opt/opencti/node_modules/grpc/src/client.js:233:26)\n    at ClientDuplexStream._receiveStatus (/opt/opencti/node_modules/grpc/src/client.js:211:8)\n    at Object.onReceiveStatus (/opt/opencti/node_modules/grpc/src/client_interceptors.js:1311:15)\n    at InterceptingListener._callNext (/opt/opencti/node_modules/grpc/src/client_int]

Apr 10 15:15:32 lab-prod-opencti OpenCTI-Server[23712]: error: [GRAKN] executeRead error > 2 UNKNOWN: Could not call index. Please check server logs for the stack trace. {"code":2,"metadata":{"_internal_repr":{},"flags":0},"details":"Could not call index. Please check server logs for the stack trace.","stack":"Error: 2 UNKNOWN: Could not call index. Please check server logs for the stack trace.\n    at Object.exports.createStatusError (/opt/opencti/node_modules/grpc/src/common.js:91:15)\n    at ClientDuplexStream._emitStatusIfDone (/opt/opencti/node_modules/grpc/src/client.js:233:26)\n    at ClientDuplexStream._receiveStatus (/opt/opencti/node_modules/grpc/src/client.js:211:8)\n    at Object.onReceiveStatus (/opt/opencti/node_modules/grpc/src/client_interceptors.js:1311:15)\n    at InterceptingListener._callNext (/opt/opencti/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/opt/opencti/node_modules/grpc/src/client_interceptors.js:618:8)\n    at /opt/opencti/node_modules/grpc/src/client_interceptors.js:1127:18"}

Apr 10 15:15:32 lab-prod-opencti OpenCTI-Server[23712]: error: [GRAKN] executeRead error > 2 UNKNOWN: Exception while executing backend operation EdgeStoreQuery. Please check server logs for the stack trace. {"code":2,"metadata":{"_internal_repr":{},"flags":0},"details":"Exception while executing backend operation EdgeStoreQuery. Please check server logs for the stack trace.","stack":"Error: 2 UNKNOWN: Exception while executing backend operation EdgeStoreQuery. Please check server logs for the stack trace.\n    at Object.exports.createStatusError (/opt/opencti/node_modules/grpc/src/common.js:91:15)\n    at ClientDuplexStream._emitStatusIfDone (/opt/opencti/node_modules/grpc/src/client.js:233:26)\n    at ClientDuplexStream._receiveStatus (/opt/opencti/node_modules/grpc/src/client.js:211:8)\n    at Object.onReceiveStatus (/opt/opencti/node_modules/grpc/src/client_interceptors.js:1311:15)\n    at InterceptingListener._callNext (/opt/opencti/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/opt/opencti/node_modules/grpc/src/client_interceptors.js:618:8)\n    at /opt/opencti/node_modules/grpc/src/client_interceptors.js:1127:18"}
```

## Environment

1. Grakn Core 1.6.2
2. client-nodejs

## Reproducible Steps

1. Run OpenCTI
2. Insert large datasets
3. Wait
4. Grakn crashes

## Expected Output

Production run indefinitely 

## Actual Output

JAVA Heap Space.
 
## Additional information

None.

**Comment by flyingsilverfin** [comment]
Are there sessions being run indefinitely? Are there long running transactions? How many inserts per transaction?

We chased down a major memory leak about 6 months ago and were seeing stable memory consumption, as long as transactions and sessions are closed properly!

**Comment by fr33tux** [comment]
Same issue here, with the same environment and a Java heap limit of 62GB.

**Comment by vmax** [comment]
Closing as it relates to an old version that's no longer supported. Please create a new one if it's reproducible with latest released 2.x version.
