### ISSUE TITLE
Null pointer on open session (javascript client) after grakn restart

### ISSUE THREAD

**Issue by richard-julien** [vaticle/typedb#5735]
## Description

Grakn client doesnt support very well a restart of the server.

## Environment

1. Windows
2. Grakn 1.7.1
3. client-nodejs ("grakn-client": "^1.7.0")

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Start grakn
2. Start a session with grakn client
3. Restart grakn
4. Try a query

## Expected Output

Query success

## Actual Output

**Grakn server error:**
```
2020-06-03 09:17:13,257 [transaction-listener] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
java.lang.NullPointerException: null
	at grakn.core.server.rpc.SessionService$TransactionListener.open(SessionService.java:328)
	at grakn.core.server.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:225)
	at grakn.core.server.rpc.SessionService$TransactionListener.lambda$onNext$1(SessionService.java:188)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Error on grakn client on the session:**
Error code: 2
```
Error: 2 UNKNOWN: null. Please check server logs for the stack trace.
    at Object.exports.createStatusError (C:\Users\Julien\Documents\Projects\opencti\opencti-platform\opencti-graphql\node_modules\grpc\src\common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (C:\Users\Julien\Documents\Projects\opencti\opencti-platform\opencti-graphql\node_modules\grpc\src\client.js:233:26)
    at ClientDuplexStream._receiveStatus (C:\Users\Julien\Documents\Projects\opencti\opencti-platform\opencti-graphql\node_modules\grpc\src\client.js:211:8)
    at Object.onReceiveStatus (C:\Users\Julien\Documents\Projects\opencti\opencti-platform\opencti-graphql\node_modules\grpc\src\client_interceptors.js:1311:15)
    at InterceptingListener._callNext (C:\Users\Julien\Documents\Projects\opencti\opencti-platform\opencti-graphql\node_modules\grpc\src\client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (C:\Users\Julien\Documents\Projects\opencti\opencti-platform\opencti-graphql\node_modules\grpc\src\client_interceptors.js:618:8)
    at C:\Users\Julien\Documents\Projects\opencti\opencti-platform\opencti-graphql\node_modules\grpc\src\client_interceptors.js:1127:18
```
 
## Additional information

Today we prevent that by catching the error code 2 and recreate the session on client side but it could be really cool that the session try to reconnect itself.

**Comment by flyingsilverfin** [comment]
@richard-julien  i was doing some small tasks, I'm hoping that for now a better error message will be sufficient: https://github.com/graknlabs/grakn/pull/5757

I'm thinking that in the future the clients should generally print better error messages and have specialised exceptions.

**Comment by flyingsilverfin** [comment]
Short term solution above, longer term solution that we decided on:

1. server should invalidate all open sessions on shutdown
2. clients should have a clean exception that are thrown when the connection is rejected (eg. if the server is still down)
3. if the server is force-shut down without invalidating all sessions, this fix applies by throwing a useful exception.

**Comment by richard-julien** [comment]
Looks like a good first approach. Any specific error code on client side for this exception? By the way to you have a list of error code than can be used on the client side?

**Comment by krishnangovindraj** [comment]
Tested on 2.14.3
```
12:55:56.538 [typedb-service::0] ERROR com.vaticle.typedb.core.server.TransactionService - [SSN01] Invalid Session Operation: Session with UUID '806e062b-b1c7-4490-930c-c3173d6f5c4b' does not exist.
```
