### ISSUE TITLE
NullPointerException on server in transaction with rule inferring option

### ISSUE THREAD

**Issue by selmeci** [vaticle/typedb#6309]
## Description

Transaction with infer option return null point exception on server

## Environment

1. OS (where Grakn server runs): Docker on Linux Mint 20.1 Cinnamon, linux kernel: 5.4.0-72-generic
2. Grakn version (and platform):
```
docker run --name grakn -d -p 1729:1729 graknlabs/grakn:latest
====================================================================================================
      ________  _____     _______  __    ___ __    __      _______  _______  _____     _______
     |   __   ||   _  \  |   _   ||  |  /  /|  \  |  |    |   _   ||   _   ||   _  \  |   ____|
     |  |  |__||  | |  | |  | |  ||  | /  / |   \ |  |    |  | |__||  | |  ||  | |  | |  |
     |  | ____ |  |_/ /  |  |_|  ||  |/  /  |    \|  |    |  |     |  | |  ||  |_/ /  |  |____
     |  ||_   ||   _  \  |   _   ||   _  \  |   _    |    |  |  __ |  | |  ||   _  \  |   ____|
     |  |__|  ||  | \  \ |  | |  ||  | \  \ |  | \   |    |  |_|  ||  |_|  ||  | \  \ |  |____
     |________||__|  \__\|__| |__||__|  \__\|__|  \__|    |_______||_______||__|  \__\|_______|

                                         THE KNOWLEDGE GRAPH
====================================================================================================
2021-04-26 08:45:04,174 [main] [INFO ] grakn.core.server.GraknServer - Grakn Core Server is now running and will keep this process alive.
2021-04-26 08:45:04,176 [main] [INFO ] grakn.core.server.GraknServer - You can press CTRL+C to shutdown this server.
2021-04-26 08:45:04,176 [main] [INFO ] grakn.core.server.GraknServer - 
2021-04-26 08:45:04,176 [main] [INFO ] grakn.core.server.GraknServer - - version: 2.0.2
2021-04-26 08:45:04,176 [main] [INFO ] grakn.core.server.GraknServer - - listening to port: 1729
2021-04-26 08:45:04,176 [main] [INFO ] grakn.core.server.GraknServer - - data directory configured to: /opt/grakn-core-all-linux/server/data
2021-04-26 08:45:04,177 [main] [INFO ] grakn.core.server.GraknServer - - bootup completed in: 465 ms
2021-04-26 08:45:04,177 [main] [INFO ] grakn.core.server.GraknServer - ...
```
3. Grakn client: java/ cli console
4. Other environment details: AMD Ryzen 9 3900X 12-Core Processor × 12, RAM 62.8 GiB, NAND SSD

## Reproducible Steps

Steps to create the smallest reproducible scenario (with files in  [test_data.zip](https://github.com/vaticle/typedb/files/6416308/test_data.zip)):
1. database create test
2. transaction test schema write
3. source /opt/grakn-core-all-linux/server/db/schema.gql
4. commit
5. transaction test data write
6. source /opt/grakn-core-all-linux/server/db/devices.gql
7. commit
8. transaction test data read --infer true
9.  query
```
match
   $this isa device, has id "Dev1";
   $other isa device, has id "Dev1";
   (this: $this, other: $this) isa this-sim-rank, has coefficient $actual;
get $actual;
```

## Expected Output

Return result according to application of rules from schema

## Actual Output

```
2021-05-03 14:48:12,277 [grakn-core-service::0] [ERROR] grakn.core.server.TransactionService - java.lang.NullPointerException
grakn.core.common.exception.GraknException: java.lang.NullPointerException
	at grakn.core.common.exception.GraknException.of(GraknException.java:51)
	at grakn.core.rocks.RocksStorage.exception(RocksStorage.java:150)
	at grakn.core.rocks.RocksStorage$TransactionBounded.exception(RocksStorage.java:278)
	at grakn.core.rocks.RocksStorage$Data.exception(RocksStorage.java:345)
	at grakn.core.graph.GraphManager.exception(GraphManager.java:55)
	at grakn.core.concept.ConceptManager.exception(ConceptManager.java:227)
	at grakn.core.query.QueryManager.match(QueryManager.java:74)
	at grakn.core.server.query.QueryService.match(QueryService.java:131)
	at grakn.core.server.query.QueryService.execute(QueryService.java:84)
	at grakn.core.server.TransactionService.executeRequest(TransactionService.java:159)
	at grakn.core.server.TransactionService.execute(TransactionService.java:135)
	at grakn.core.server.TransactionService.onNext(TransactionService.java:115)
	at grakn.core.server.TransactionService.onNext(TransactionService.java:74)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:255)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: null
	at java.base/java.lang.String.<init>(String.java:614)
	at grakn.core.graph.structure.impl.RuleStructureImpl$Persisted.<init>(RuleStructureImpl.java:252)
	at grakn.core.graph.SchemaGraph$Rules.lambda$convert$1(SchemaGraph.java:425)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at grakn.core.graph.SchemaGraph$Rules.convert(SchemaGraph.java:424)
	at grakn.core.common.iterator.MappedIterator.next(MappedIterator.java:40)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at grakn.core.common.iterator.AbstractFunctionalIterator.toSet(AbstractFunctionalIterator.java:187)
	at grakn.core.graph.SchemaGraph$Rules$Conclusions$Persisted.loadConcludesVertex(SchemaGraph.java:604)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at grakn.core.graph.SchemaGraph$Rules$Conclusions$Persisted.concludesVertex(SchemaGraph.java:577)
	at grakn.core.graph.SchemaGraph$Rules$Conclusions.concludesVertex(SchemaGraph.java:542)
	at grakn.core.logic.LogicManager.rulesConcluding(LogicManager.java:95)
	at grakn.core.reasoner.Reasoner.hasRule(Reasoner.java:107)
	at grakn.core.common.iterator.FilteredIterator.fetchAndCheck(FilteredIterator.java:41)
	at grakn.core.common.iterator.FilteredIterator.hasNext(FilteredIterator.java:37)
	at grakn.core.common.iterator.AbstractFunctionalIterator.anyMatch(AbstractFunctionalIterator.java:104)
	at grakn.core.reasoner.Reasoner.mayReason(Reasoner.java:100)
	at grakn.core.reasoner.Reasoner.mayReason(Reasoner.java:93)
	at grakn.core.reasoner.Reasoner.execute(Reasoner.java:118)
	at grakn.core.query.Matcher.execute(Matcher.java:125)
	at grakn.core.query.Matcher.execute(Matcher.java:121)
	at grakn.core.query.QueryManager.match(QueryManager.java:72)
	... 15 common frames omitted
```
 
## Additional information

Rules used in query:
```
rule device-identity-similarity:
when {
    $this isa device;
} then {
     (this: $this, other: $this) isa this-sim-rank;
};

rule device-identity-similarity-is-one:
when {
    $this isa device;
    $s (this: $this, other: $this) isa this-sim-rank;
} then {
    $s has coefficient 1.0;
};
```

**Comment by flyingsilverfin** [comment]
Hi - is there any chance that this example overwrites a rule at any point? https://github.com/vaticle/typedb/issues/6311 is similar but caused by adding a rule with the same name twice.

**Comment by selmeci** [comment]
Hi - I'm not sure what are you meaning by "this example overwrites a rule".

Input data does not contain any relations of the type `this-sim-rank`. I would like to infer by rule that device has similarity equals to 1.0 with itself.

In my case I do not redefine schema and both rules has different names. And my error is not in client side but on server.

**Comment by flyingsilverfin** [comment]
ok, i will look into this as a contination of the other issue now

**Comment by flyingsilverfin** [comment]
So i followed your steps and failed to reproduce the issue - do you mind applying them yourself to an empty database on your typeDB distribution and verifying that you do see the issue please?

**Comment by selmeci** [comment]
Sorry my mistake. It's probably same issue like in #6311. Maybe I rewrite schema and forgot that I did it :).

You can reproduce error if you repeat steps 2,3,4 twice.

1. database create test
2.transaction test schema write
3. source /opt/grakn-core-all-linux/server/db/schema.gql
4. commit
5. transaction test data write
6. source /opt/grakn-core-all-linux/server/db/devices.gql
7. commit
8. transaction test data read --infer true
9. query

query is working. Do 2,3,4 again without any changes in schema.

1. transaction test schema write
2. source /opt/grakn-core-all-linux/server/db/schema.gql
3. commit
4. transaction test data read --infer true
5. query

error is thrown.

**Comment by flyingsilverfin** [comment]
ok, sounds like the same!
