### ISSUE TITLE
Null Pointer Exception in Python client upon redefining a rule without undefining it before

### ISSUE THREAD

**Issue by hkuich** [vaticle/typedb#6311]
## Description

@flyingsilverfin : as discussed...

1) define schema
2) define rule
3) queries both from console and python client are OK
4) redefine same rule
5) query from console OK, python client throws null pointer

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): 2.0.2
3. Grakn client: console & client-python 2.0.1
4. Other environment details:

## Reproducible Steps

1) adjust console paths in all .sh files

2) ```bash break_it.sh``` in attached.

## Additional information

```
Traceback (most recent call last):
  File "firequery.py", line 20, in <module>
    for answer in answer_it:
  File "python3.8/site-packages/grakn/query/query_manager.py", line 54, in <genexpr>
    return (_ConceptMap.of(cm) for rp in self.stream(query_manager_match_req(query, options.proto())) for cm in rp.match_res_part.answers)
  File "python3.8/site-packages/grakn/query/query_manager.py", line 110, in <genexpr>
    return (rp.query_manager_res_part for rp in self._transaction_ext.stream(req))
  File "python3.8/site-packages/grakn/stream/response_part_iterator.py", line 78, in __next__
    if not self._has_next():
  File "python3.8/site-packages/grakn/stream/response_part_iterator.py", line 73, in _has_next
    return self._fetch_and_check()
  File "python3.8/site-packages/grakn/stream/response_part_iterator.py", line 48, in _fetch_and_check
    res_part = self._bidirectional_stream.fetch(self._request_id)
  File "site-packages/grakn/stream/bidirectional_stream.py", line 80, in fetch
    raise GraknClientException.of_rpc(e)
grakn.common.exception.GraknClientException: java.lang.NullPointerException: Cannot read the array length because "bytes" is null Please check server logs for the stack trace.
```
[redefine-rule-python-client-bug.zip](https://github.com/vaticle/typedb/files/6423028/redefine-rule-python-client-bug.zip)

**Comment by flyingsilverfin** [comment]
For the record i think this breaks in python but not the console because the reproducible example doesn't enable reasoning in console ;)

looking into the error now
