### ISSUE TITLE
Uncaught exception thrown at thread 'logback-3: Java heap space'

### ISSUE THREAD

**Issue by JonThom** [vaticle/typedb#6326]
## Description

I was performing insert queries to add a new unique identifier attribute (in batches of 50 queries per commit) to every entity and relation in the biograkn covid database.
The identifiers were generated using uuid4() from the uuid module (see snippet below).

The new attributes were successfully inserted for all entities, but for least for a subset of relations, TypeDB encountered a `java.lang.OutOfMemoryError: Java heap space` error.

## Environment

1. OS (where TypeDB server runs): Mac OS 10
2. TypeDB version (and platform): TypeDB 2.0.2
3. TypeDB client: client-python
4. Processor 3.3 GHz Intel Core i5, Memory 16 GB 2133 MHz LPDDR3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. start the typedb server 
2. migrate the biograkn covid database (the database where the error occured) - alternatively, any other large typedb database
3. define a new attributeType which is owned by all relationTypes - here "UID"
4. iterate over all instances of relation- and attributeTypes, assigning individual values for the new attribute. This last step is shown below, where we only add the attributes to relations, which seemed to be where the error occurred.

```
# UID attribute should already be defined and owned by all relationTypes

import uuid 
new_attr_label = "UID"
host="localhost"
port = "1729"
batch_size = 50

def thing_modifier(write_transaction, thing, new_attr_label):
    query = "match $x iid {0}; insert $x has {1} '{2}'; ".format(thing.get_iid(), new_attr_label, str(uuid.uuid4()))   
    write_transaction.query().insert(query)

with Grakn.core_client(address=host+":"+port) as client:
    with client.session(database, SessionType.DATA) as session:
        with session.transaction(TransactionType.READ) as read_transaction:
            iterator_conceptMap = read_transaction.query().match("$x isa relation; ")
            k = 1
            write_transaction = session.transaction(TransactionType.WRITE)
            while True:
                try:
                    conceptMap = next(iterator_conceptMap)
                    thing_modifier(write_transaction, conceptMap.get("x"), *args)
                except:
                    # iterator is exhausted
                    write_transaction.commit()
                    break
                if batch_size%k == 0:
                    write_transaction.commit()
                    write_transaction = session.transaction(TransactionType.WRITE)
                k+=1
```
## Expected Output

Expecting all matching things (here, all relations) to be assigned new UID attribute.

## Actual Output

At some point (possibly right at the beginning, not sure, sorry), the following error occurred:

> 2021-05-16 21:50:46,198 [logback-3] [ERROR] grakn.core.server.GraknServer - [SRV04] Invalid Server Operation: Uncaught exception thrown at thread 'logback-3: Java heap space'.
> java.lang.OutOfMemoryError: Java heap space
> May 16, 2021 9:50:32 PM io.grpc.internal.SerializingExecutor run
> SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@5056c9ed
> java.util.concurrent.RejectedExecutionException: event executor terminated
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818)
> 	at io.grpc.netty.WriteQueue.scheduleFlush(WriteQueue.java:67)
> 	at io.grpc.netty.NettyServerStream$Sink.writeFrameInternal(NettyServerStream.java:112)
> 	at io.grpc.netty.NettyServerStream$Sink.writeFrame(NettyServerStream.java:137)
> 	at io.grpc.internal.AbstractServerStream.deliverFrame(AbstractServerStream.java:111)
> 	at io.grpc.internal.MessageFramer.commitToSink(MessageFramer.java:352)
> 	at io.grpc.internal.MessageFramer.close(MessageFramer.java:328)
> 	at io.grpc.internal.AbstractStream.endOfMessages(AbstractStream.java:84)
> 	at io.grpc.internal.AbstractServerStream.close(AbstractServerStream.java:120)
> 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.internalClose(ServerImpl.java:763)
> 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.access$3000(ServerImpl.java:723)
> 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:784)
> 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
> 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by JonThom** [comment]
Update: this also happened with batches of 25 transactions per commit

**Comment by JonThom** [comment]
This was due to a bug in the condition for when to commit: `if batch_size%k == 0` should be  `if k%batch_size == 0`
