### ISSUE TITLE
Matching for a relation playing a role in itself throws internal errors

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#6367]
## Description

Matching for a relation playing a role in itself throws internal errors. Two different internal errors have been observed depending upon the exact circumstances, and we have added a test for each.

This was highlighted by https://github.com/vaticle/typedb/issues/6359, which already required minor fixes in reasoner in https://github.com/vaticle/typedb/pull/6366.

## Environment

1. OS (where TypeDB server runs): Mac OS 10
2. TypeDB version (and platform): TypeDB as of this PR: https://github.com/vaticle/typedb/pull/6366
3. TypeDB client: console

## Reproducible Steps

Steps to create the smallest reproducible scenario:
- Use the scenarios introduced [here](https://github.com/vaticle/typedb-behaviour/pull/202) (currently ignored)

## Expected Output

Both should correctly find one answer via match.

## Actual Output

Test: `A relation can play a role in itself`
Output: 
```
com.vaticle.typedb.core.common.exception.TypeDBException: [INT03] Invalid Internal State: Illegal internal operation! This method should not have been called.
com.vaticle.typedb.core.common.exception.TypeDBException: 
	at com.vaticle.typedb.core.common.exception.TypeDBException.of(TypeDBException.java:51)
	at com.vaticle.typedb.core.concurrent.producer.ProducerIterator.hasNext(ProducerIterator.java:100)
	at com.vaticle.typedb.core.common.iterator.ErrorHandledIterator.hasNext(ErrorHandledIterator.java:38)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at com.vaticle.typedb.core.common.iterator.AbstractFunctionalIterator.toList(AbstractFunctionalIterator.java:136)
	at com.vaticle.typedb.core.test.behaviour.typeql.TypeQLSteps.typeql_match(TypeQLSteps.java:153)
	at ✽.get answers of typeql match(file:///private/var/tmp/_bazel_jamesfletcher/91bfc2886b4509aa35a584e846a96d83/execroot/vaticle_typedb/bazel-out/darwin-fastbuild/bin/test/behaviour/debug/test.runfiles/vaticle_typedb/test/behaviour/debug/debug.feature:76)
Caused by: 
	at com.vaticle.typedb.core.common.exception.TypeDBException.of(TypeDBException.java:55)
	at com.vaticle.typedb.core.traversal.procedure.ProcedureEdge$Native$Thing$RolePlayer.isClosure(ProcedureEdge.java:998)
	at com.vaticle.typedb.core.traversal.procedure.VertexProcedure.lambda$iterator$1(VertexProcedure.java:106)
	at com.vaticle.typedb.core.common.iterator.FilteredIterator.fetchAndCheck(FilteredIterator.java:41)
	at com.vaticle.typedb.core.common.iterator.FilteredIterator.hasNext(FilteredIterator.java:37)
	at com.vaticle.typedb.core.common.iterator.MappedIterator.hasNext(MappedIterator.java:35)
	at com.vaticle.typedb.core.common.iterator.DistinctIterator.fetchAndCheck(DistinctIterator.java:48)
	at com.vaticle.typedb.core.common.iterator.DistinctIterator.hasNext(DistinctIterator.java:44)
	at com.vaticle.typedb.core.common.iterator.MappedIterator.hasNext(MappedIterator.java:35)
	at com.vaticle.typedb.core.concurrent.producer.BaseProducer.lambda$produce$0(BaseProducer.java:64)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

Test: `A relation can play a role in itself and have additional roleplayers`
Output:
```
java.lang.AssertionError
	at com.vaticle.typedb.core.traversal.planner.PlannerVertex.setHasIncomingEdgesInitial(PlannerVertex.java:203)
	at com.vaticle.typedb.core.traversal.planner.GraphPlanner$Initialiser.lambda$execute$3(GraphPlanner.java:456)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.vaticle.typedb.core.traversal.planner.GraphPlanner$Initialiser.execute(GraphPlanner.java:454)
	at com.vaticle.typedb.core.traversal.planner.GraphPlanner.setInitialValues(GraphPlanner.java:324)
	at com.vaticle.typedb.core.traversal.planner.GraphPlanner.updateObjective(GraphPlanner.java:270)
	at com.vaticle.typedb.core.traversal.planner.GraphPlanner.optimise(GraphPlanner.java:351)
	at com.vaticle.typedb.core.traversal.planner.GraphPlanner.mayOptimise(GraphPlanner.java:335)
	at com.vaticle.typedb.core.traversal.planner.Planner.tryOptimise(Planner.java:34)
	at com.vaticle.typedb.core.traversal.Traversal.producer(Traversal.java:131)
	at com.vaticle.typedb.core.traversal.TraversalEngine.producer(TraversalEngine.java:56)
	at com.vaticle.typedb.core.traversal.TraversalEngine.producer(TraversalEngine.java:50)
	at com.vaticle.typedb.core.reasoner.Reasoner.producer(Reasoner.java:159)
	at com.vaticle.typedb.core.reasoner.Reasoner.lambda$executeTraversal$6(Reasoner.java:151)
	at com.vaticle.typedb.core.common.iterator.MappedIterator.next(MappedIterator.java:40)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at com.vaticle.typedb.core.common.iterator.AbstractFunctionalIterator.toList(AbstractFunctionalIterator.java:136)
	at com.vaticle.typedb.core.reasoner.Reasoner.executeTraversal(Reasoner.java:151)
	at com.vaticle.typedb.core.reasoner.Reasoner.execute(Reasoner.java:119)
	at com.vaticle.typedb.core.query.Matcher.execute(Matcher.java:125)
	at com.vaticle.typedb.core.query.Matcher.execute(Matcher.java:121)
	at com.vaticle.typedb.core.query.QueryManager.match(QueryManager.java:72)
	at com.vaticle.typedb.core.query.QueryManager.match(QueryManager.java:67)
	at com.vaticle.typedb.core.test.behaviour.typeql.TypeQLSteps.typeql_match(TypeQLSteps.java:153)
	at ✽.get answers of typeql match(file:///private/var/tmp/_bazel_jamesfletcher/91bfc2886b4509aa35a584e846a96d83/execroot/vaticle_typedb/bazel-out/darwin-fastbuild/bin/test/behaviour/debug/test.runfiles/vaticle_typedb/test/behaviour/debug/debug.feature:107)
```

**Comment by flyingsilverfin** [comment]
Fixed by traversal engine rewrite in #6468  and f38a7f15becd98640bd5d43204d1e05bb07cf718
