### ISSUE TITLE
Customizing `server.logs` to a location outside the typedb folder has no effect

### ISSUE THREAD

**Issue by haskie-lambda** [vaticle/typedb#6370]
## Description

Using 
```
typedb server --data=/path/to/some/directory/other/than/the/install/location \
                      --logs=/path/to/some/directory/other/than/the/install/location
```
results in the following log:
```
15:06:43,618 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
15:06:43,619 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
15:06:43,620 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/nix/store/0fp1967g51vp872034kz504r7bxgpmg6-typedb-2.1.1/server/conf/logback.xml]
15:06:43,698 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
15:06:43,703 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/nix/store/0fp1967g51vp872034kz504r7bxgpmg6-typedb-2.1.1/server/conf/logback.xml] 
15:06:43,703 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 30 seconds
15:06:43,709 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:06:43,713 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
15:06:43,721 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:06:43,788 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
15:06:43,791 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [LOGFILE]
15:06:43,792 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:06:43,796 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@699780352 - setting totalSizeCap to 1 GB
15:06:43,797 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@699780352 - Archive files will be limited to [50 MB] each.
15:06:43,799 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@699780352 - Will use gz compression
15:06:43,799 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@699780352 - Will use the pattern /nix/store/0fp1967g51vp872034kz504r7bxgpmg6-typedb-2.1.1/server/logs//typedb.log-%d{yyyy-MM}.%i.log for the active file
15:06:43,801 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@60285225 - The date pattern is 'yyyy-MM' from file name pattern '/nix/store/0fp1967g51vp872034kz504r7bxgpmg6-typedb-2.1.1/server/logs//typedb.log-%d{yyyy-MM}.%i.log.gz'.
15:06:43,801 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@60285225 - Rollover at start of every month.
15:06:43,808 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@60285225 - Setting initial period to Thu Jan 01 01:00:01 CET 1970
15:06:43,811 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[LOGFILE] - Active log file name: /nix/store/0fp1967g51vp872034kz504r7bxgpmg6-typedb-2.1.1/server/logs//typedb.log
15:06:43,811 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[LOGFILE] - File property is set to [/nix/store/0fp1967g51vp872034kz504r7bxgpmg6-typedb-2.1.1/server/logs//typedb.log]
15:06:43,812 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[LOGFILE] - openFile(/nix/store/0fp1967g51vp872034kz504r7bxgpmg6-typedb-2.1.1/server/logs//typedb.log,true) call failed. java.io.FileNotFoundException: /nix/store/0fp1967g51vp872034kz504r7bxgpmg6-typedb-2.1.1/server/logs/typedb.log (Permission denied)
	at java.io.FileNotFoundException: /nix/store/0fp1967g51vp872034kz504r7bxgpmg6-typedb-2.1.1/server/logs/typedb.log (Permission denied)
	at 	at java.base/java.io.FileOutputStream.open0(Native Method)
	at 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
	at 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at 	at com.vaticle.typedb.core.server.TypeDBServer.<clinit>(TypeDBServer.java:64)
15:06:43,812 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
15:06:43,812 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.vaticle.typedb.core] to INFO
15:06:43,812 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [LOGFILE] to Logger[com.vaticle.typedb.core]
15:06:43,812 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[com.vaticle.typedb.core]
15:06:43,812 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:06:43,813 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@cb51256 - Registering current configuration as safe fallback point


================================================================
     ________ __      __ _____    _______  _____    _____
    |__    __|\  \  /  /|   _  \ |   _   ||   _  \ |   _  \
       |  |    \  \/  / |  | |  ||  | |__||  | |  ||  | |  |
       |  |     \    /  |  |/  / |  |___  |  | |  ||  |/  /
       |  |      |  |   |   __/  |   ___| |  | |  ||   _  \
       |  |      |  |   |  |     |  |  __ |  | |  ||  | |  |
       |  |      |  |   |  |     |  |_|  ||  |/  / |  |/  /
       |__|      |__|   |__|     |_______||_____/  |_____/

                    A STRONGLY-TYPED DATABASE
================================================================

2021-06-10 15:06:44,875 [main] [INFO ] c.v.typedb.core.server.TypeDBServer - TypeDB Server is now running and will keep this process alive.
2021-06-10 15:06:44,877 [main] [INFO ] c.v.typedb.core.server.TypeDBServer - You can press CTRL+C to shutdown this server.
2021-06-10 15:06:44,877 [main] [INFO ] c.v.typedb.core.server.TypeDBServer - 
2021-06-10 15:06:44,877 [main] [INFO ] c.v.typedb.core.server.TypeDBServer - - version: 2.1.1
2021-06-10 15:06:44,877 [main] [INFO ] c.v.typedb.core.server.TypeDBServer - - listening to port: 1729
2021-06-10 15:06:44,877 [main] [INFO ] c.v.typedb.core.server.TypeDBServer - - data directory configured to: /home/faebl/.typedb_home/data
2021-06-10 15:06:44,877 [main] [INFO ] c.v.typedb.core.server.TypeDBServer - - bootup completed in: 914 ms
2021-06-10 15:06:44,877 [main] [INFO ] c.v.typedb.core.server.TypeDBServer - ...
^C2021-06-10 15:08:41,525 [TypeDBServer::shutdown::0] [INFO ] c.v.typedb.core.server.TypeDBServer - 
2021-06-10 15:08:41,525 [TypeDBServer::shutdown::0] [INFO ] c.v.typedb.core.server.TypeDBServer - Shutting down TypeDB Server...
2021-06-10 15:08:41,565 [TypeDBServer::shutdown::0] [INFO ] c.v.typedb.core.server.TypeDBServer - TypeDB Server has been shutdown
```

suggesting that the `data directory` is set correctly, yet for the `logs directory` the default is used;
(which in this case is a readonly directory).

Connected to [this discussion](https://discord.com/channels/665254494820368395/672583211477631035/852546787566944287)

## Environment

1. OS (where TypeDB server runs): NixOS 20.09
2. TypeDB version (and platform): TypeDB 2.1.1
3. TypeDB client: console
4. Other environment details: [installation with wrapper script via nix-package manager](https://github.com/NixOS/nixpkgs/pull/125350)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. install typedb in a readonly location
2. run typedb with --data and --logs set to a writable directory unrelated to the install location
3. error will be similar to above

alternatively:
1. install nix package manager
2. [checkout https://github.com/NixOS/nixpkgs/pull/125350](https://github.com/NixOS/nixpkgs/pull/125350)
4. `sudo nix-build --option build-use-sandbox true -A typedb`
5. `./result/bin/typedb server`

## Expected Output

logging folder and logfiles should be produced and written in the specified directory

## Actual Output

logging folder and logfiles are specified to be in the default location
 
## Additional information

**Comment by lolski** [comment]
Thanks for submitting the issue. I see two bugs regarding attempting to configure the log directory path:

1. The logs will always be inside the distribution directory

    If we attempt to configure it to `/var/log/typeb` they will be located in `dist/typedb-all-linux//var/log/typeb`. This is because we always prefix the logs directory with `${typedb.dir}`: `<property name="directory" value="${typedb.dir}/${server.logs}"/>`.

2. The configuration can't be overridden from CLI options

    If you attempt to overrided the options like this: `./typedb server. --logs=server/logs2`, they will be ignored. This is because `logback.xml` only reads from `typedb.properties`: `<property resource="typedb.properties"/>`

**Comment by flyingsilverfin** [comment]
The issues here have been resolved and will be released in the next version :)
