### ISSUE TITLE
Undefining Type throws NullPointer if declared parent type doesn't exist

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#6379]
## Description

Undefining a type, declaring that it subtypes a type that doesn't exist, throws a NullPointerException.

## Environment

1. OS (where TypeDB server runs): Mac OS 10
2. TypeDB version (and platform): TypeDB 2.1.2
3. TypeDB client: Found in integration test

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Try this in an integration test, having defined any valid rule called `my-rule`:
```
tx.query().undefine(TypeQL.undefine(TypeQL.type("my-rule").sub("rule")));
```
Above is the Grakn 1.x syntax for undefining a rule, so is an easy mistake to make in TypeDB 2.x, which is how I came across this bug.

The correct way would be:
```
tx.query().undefine(TypeQL.undefine(Collections.singletonList(TypeQL.rule("my-rule"))));
```

## Expected Output

We expect that 

## Actual Output

```
java.lang.NullPointerException: Cannot invoke "com.vaticle.typedb.core.concept.type.ThingType.isRoleType()" because "thingType" is null
com.vaticle.typedb.core.common.exception.TypeDBException: 
	at com.vaticle.typedb.core.common.exception.TypeDBException.of(TypeDBException.java:51)
	at com.vaticle.typedb.core.rocks.RocksStorage.exception(RocksStorage.java:139)
	at com.vaticle.typedb.core.rocks.RocksStorage$TransactionBounded.exception(RocksStorage.java:274)
	at com.vaticle.typedb.core.rocks.RocksStorage$Data.exception(RocksStorage.java:325)
	at com.vaticle.typedb.core.graph.GraphManager.exception(GraphManager.java:55)
	at com.vaticle.typedb.core.concept.ConceptManager.exception(ConceptManager.java:228)
	at com.vaticle.typedb.core.query.QueryManager.undefine(QueryManager.java:184)
	at com.vaticle.typedb.core.query.QueryManager.undefine(QueryManager.java:175)
	at com.vaticle.typedb.core.test.behaviour.resolution.framework.test.TestResolution.testResolutionThrowsForTransitivityWhenRuleTriggersTooOften(TestResolution.java:107)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:108)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:116)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:159)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:85)
Caused by: 
	at com.vaticle.typedb.core.query.Undefiner.undefineSub(Undefiner.java:163)
	at com.vaticle.typedb.core.query.Undefiner.undefine(Undefiner.java:133)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.vaticle.typedb.core.query.Undefiner.execute(Undefiner.java:106)
	at com.vaticle.typedb.core.query.QueryManager.undefine(QueryManager.java:182)
	... 27 more
```
 
## Additional information

Looking at the code, the culprit is clear. `Undefiner.getThingType` returns `null` if the type doesn't exist, but there is no defence for the case where it is `null`. I haven't fixed this immediately because there are multiple places within `Definer` which return or expect `null`, or which `.get()` from an `Optional` without an `isPresent()` check. These should all be considered together. They all receive yellow underlines from IntelliJ.

**Comment by flyingsilverfin** [comment]
Doesn't exist in 2.11.x, and a variant is fixed in https://github.com/vaticle/typedb/pull/6631
