### ISSUE TITLE
Background thread ACID violation

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#6401]
## Description

We encounter a concurrent modification error in a statistics background thread when running a highly parallel job. This may be an expected error case, but if that is true it is unexpected that this background job failure would kill the server.

## Environment

1. OS (where TypeDB server runs): Grabl
2. TypeDB version (and platform): `d08dd7339d134018644736cd625ecc04f7b87e5b`
3. TypeDB client: client-java

## Reproducible Steps

Steps to create the smallest reproducible scenario:
- Run a benchmark job with the new `MarriageAgent` and `ParenthooAgent`. Have seen the failure once so far at approx iteration 20.

## Expected Output

No error should have been thrown

## Actual Output

```
2021-07-12 18:05:59,617 [simulation::statistics-background-counter::0] [ERROR] c.v.typedb.core.server.TypeDBServer - [SRV04] Invalid Server Operation: Uncaught exception thrown at thread 'simulation::statistics-background-counter::0: [TXN10] Invalid Transaction Operation: The transaction deletes a key that is concurrently modified.'.
com.vaticle.typedb.core.common.exception.TypeDBException: [TXN10] Invalid Transaction Operation: The transaction deletes a key that is concurrently modified.
at com.vaticle.typedb.core.common.exception.TypeDBException.of(TypeDBException.java:55)
at com.vaticle.typedb.core.rocks.RocksDatabase$ConsistencyManager.tryCommitOptimistically(RocksDatabase.java:372)
at com.vaticle.typedb.core.rocks.RocksStorage$Data.commit(RocksStorage.java:412)
at com.vaticle.typedb.core.rocks.RocksTransaction$Data.commit(RocksTransaction.java:296)
at com.vaticle.typedb.core.rocks.RocksDatabase$StatisticsBackgroundCounter.countFn(RocksDatabase.java:613)
at java.base/java.lang.Thread.run(Thread.java:829)
```
 
## Additional information

The log for this failing job is here:
https://grabl.io/jmsfltchr/typedb-benchmark/858ddc513d1452cbde3a5aab1e7b888ba5143afe/build/1/performance/1/test-performance-typedb-core-server/1
(may become outdated quickly)

**Comment by flyingsilverfin** [comment]
Closing since we've rewritten both the ACID conflict detection and the background statistics counter, we can re-open if it appears again
