### ISSUE TITLE
TypeDBClientException: [TYR03] Invalid Type Read: The type 'name' does not exist. Please check server logs for the stack trace.

### ISSUE THREAD

**Issue by SaqlainHussainShah** [vaticle/typedb#6424]
## Description

{I am trying to run [this example](https://docs.vaticle.com/docs/examples/phone-calls-migration-python) . I have created databse with name phone_calls but when i run python code I get this error  }

## Environment

1. OS (where TypeDB server runs): { Ubuntu 18}
2. TypeDB version (and platform): {  TypeDB 2.0.0 }
3. TypeDB client: { client-python }

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { created database }
2. { Run [this code](https://docs.vaticle.com/docs/examples/phone-calls-migration-python)  }
3. { Gets error }
4. { e.g. See error ... }

This is inside log file

{ 2021-08-16 16:38:41,572 [typedb-service::0] [ERROR] c.v.t.core.server.TransactionService - [TYR03] Invalid Type Read: The type 'name' does not exist.
com.vaticle.typedb.core.common.exception.TypeDBException: [TYR03] Invalid Type Read: The type 'name' does not exist.
	at com.vaticle.typedb.core.common.exception.TypeDBException.of(TypeDBException.java:55)
	at com.vaticle.typedb.core.query.Inserter$Operation.getThingType(Inserter.java:219)
	at com.vaticle.typedb.core.query.Inserter$Operation.insertIsa(Inserter.java:227)
	at com.vaticle.typedb.core.query.Inserter$Operation.insert(Inserter.java:205)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1083)
	at com.vaticle.typedb.core.query.Inserter$Operation.execute(Inserter.java:177)
	at com.vaticle.typedb.core.query.Inserter.execute(Inserter.java:137)
	at com.vaticle.typedb.core.query.QueryManager.insert(QueryManager.java:126)
	at com.vaticle.typedb.core.server.query.QueryService.insert(QueryService.java:158)
	at com.vaticle.typedb.core.server.query.QueryService.execute(QueryService.java:96)
	at com.vaticle.typedb.core.server.TransactionService.executeRequest(TransactionService.java:160)
	at com.vaticle.typedb.core.server.TransactionService.execute(TransactionService.java:136)
	at com.vaticle.typedb.core.server.TransactionService.onNext(TransactionService.java:116)
	at com.vaticle.typedb.core.server.TransactionService.onNext(TransactionService.java:75)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:255)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834). }

**Comment by SaqlainHussainShah** [comment]
The issue was that I missed creating schema. Thanks
