### ISSUE TITLE
Improve error message for MacOS M1 chip users

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb#6547]
## Problem to Solve

MacBook M1 users get the following unhelpful error message on server startup:
```
================================================================
     ________ __      __ _____    _______  _____    _____
    |__    __|\  \  /  /|   _  \ |   _   ||   _  \ |   _  \
       |  |    \  \/  / |  | |  ||  | |__||  | |  ||  | |  |
       |  |     \    /  |  |/  / |  |___  |  | |  ||  |/  /
       |  |      |  |   |   __/  |   ___| |  | |  ||   _  \
       |  |      |  |   |  |     |  |  __ |  | |  ||  | |  |
       |  |      |  |   |  |     |  |_|  ||  |/  / |  |/  /
       |__|      |__|   |__|     |_______||_____/  |_____/

                    A STRONGLY-TYPED DATABASE
================================================================

Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/ry/bnfxqrqd1bd4mxtvgvnsr9j80000gn/T/librocksdbjni18708461303295440.jnilib: dlopen(/private/var/folders/ry/bnfxqrqd1bd4mxtvgvnsr9j80000gn/T/librocksdbjni18708461303295440.jnilib, 1): no suitable image found.  Did find:
	/private/var/folders/ry/bnfxqrqd1bd4mxtvgvnsr9j80000gn/T/librocksdbjni18708461303295440.jnilib: mach-o, but wrong architecture
	/private/var/folders/ry/bnfxqrqd1bd4mxtvgvnsr9j80000gn/T/librocksdbjni18708461303295440.jnilib: mach-o, but wrong architecture
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:79)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:57)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:69)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:38)
	at com.vaticle.typedb.core.rocks.RocksTypeDB.<clinit>(RocksTypeDB.java:47)
	at com.vaticle.typedb.core.rocks.RocksFactory.typedb(RocksFactory.java:34)
	at com.vaticle.typedb.core.server.TypeDBServer.<init>(TypeDBServer.java:88)
	at com.vaticle.typedb.core.server.TypeDBServer.<init>(TypeDBServer.java:72)
	at com.vaticle.typedb.core.server.TypeDBServer.runServer(TypeDBServer.java:244)
	at com.vaticle.typedb.core.server.TypeDBServer.main(TypeDBServer.java:225)
```

## Proposed Solution

We should detect MacOS M1 architecture running on a non-x64 JDK and give a better error message, something like: "The installed JDK is not compatible with TypeDB, please use a JDK build that targets x64 architecture. See https://forum.vaticle.com/t/running-typedb-on-an-m1-macbook/53 for details"

**Comment by dmitrii-ubskii** [comment]
Will be made obsolete when native ARM build is available. Cf. #6255.
