### ISSUE TITLE
Unification satisfiable throws NoSuchElementException

### ISSUE THREAD

**Issue by tomassabat** [vaticle/typedb#6566]
## Description

Running a query produces an unhandled exception. The notable feature here is that there is a role-player inside rule conclusions that is left un-declared, to be inferred by type inference in the rule body. 

## Environment

TypeDB version: TypeDB 2.10.0
OS of TypeDB server: Mac OS 12.1
Studio version: From master commit: 4da5eaf
OS of Studio: Mac OS 12.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Load schema and data
2. Run this query: 

```
match 
$kitchen isa room, has room-name "kitchen";
$bedroom isa room, has room-name "bedroom";
(place: $kitchen, place:  $bedroom, door-connector: $doors) isa room-connection;
```

## Actual Output
```java
16:48:11.355 [typedb-actor::2] ERROR com.vaticle.typedb.core.reasoner.controller.AbstractController - Actor exception
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at com.vaticle.typedb.core.logic.resolvable.Concludable$Relation.unificationSatisfiable(Concludable.java:434)
	at com.vaticle.typedb.core.logic.resolvable.Concludable$Relation.lambda$matchRolePlayers$5(Concludable.java:398)
	at com.vaticle.typedb.core.common.iterator.FilteredIterator.fetchAndCheck(FilteredIterator.java:41)
	at com.vaticle.typedb.core.common.iterator.FilteredIterator.hasNext(FilteredIterator.java:37)
	at com.vaticle.typedb.core.common.iterator.MappedIterator.hasNext(MappedIterator.java:35)
	at com.vaticle.typedb.core.common.iterator.FlatMappedIterator.fetchAndCheck(FlatMappedIterator.java:52)
	at com.vaticle.typedb.core.common.iterator.FlatMappedIterator.hasNext(FlatMappedIterator.java:48)
	at com.vaticle.typedb.core.common.iterator.FlatMappedIterator.fetchAndCheck(FlatMappedIterator.java:52)
	at com.vaticle.typedb.core.common.iterator.FlatMappedIterator.hasNext(FlatMappedIterator.java:48)
	at com.vaticle.typedb.core.common.iterator.MappedIterator.hasNext(MappedIterator.java:35)
	at com.vaticle.typedb.core.common.iterator.FunctionalIterator.forEachRemaining(FunctionalIterator.java:104)
	at com.vaticle.typedb.core.logic.resolvable.Concludable$Relation.lambda$applicableRules$12(Concludable.java:450)
	at com.vaticle.typedb.core.common.iterator.FunctionalIterator.forEachRemaining(FunctionalIterator.java:105)
	at com.vaticle.typedb.core.logic.resolvable.Concludable$Relation.lambda$applicableRules$13(Concludable.java:449)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.vaticle.typedb.core.logic.resolvable.Concludable$Relation.applicableRules(Concludable.java:448)
	at com.vaticle.typedb.core.logic.resolvable.Concludable.getApplicableRules(Concludable.java:112)
	at
com.vaticle.typedb.core.reasoner.controller.RootConjunctionController.lambda$concludablesTriggeringRules$1(RootConjunctionController.java:70)
	at com.vaticle.typedb.core.common.iterator.FilteredIterator.fetchAndCheck(FilteredIterator.java:41)
	at com.vaticle.typedb.core.common.iterator.FilteredIterator.hasNext(FilteredIterator.java:37)
	at com.vaticle.typedb.core.common.iterator.FunctionalIterator.forEachRemaining(FunctionalIterator.java:104)
	at com.vaticle.typedb.core.common.iterator.AbstractFunctionalIterator.toSet(AbstractFunctionalIterator.java:198)
	at com.vaticle.typedb.core.reasoner.controller.RootConjunctionController.concludablesTriggeringRules(RootConjunctionController.java:71)
	at com.vaticle.typedb.core.reasoner.controller.ConjunctionController.setUpUpstreamControllers(ConjunctionController.java:88)
	at com.vaticle.typedb.core.reasoner.controller.RootConjunctionController.initialise(RootConjunctionController.java:55)
	at com.vaticle.typedb.core.reasoner.controller.ControllerRegistry.lambda$createRootController$6(ControllerRegistry.java:131)
	at com.vaticle.typedb.core.concurrent.actor.Actor$Driver.lambda$execute$0(Actor.java:80)
	at com.vaticle.typedb.core.concurrent.actor.ActorExecutor$Task.run(ActorExecutor.java:127)
	at com.vaticle.typedb.core.concurrent.actor.ActorExecutor.run(ActorExecutor.java:71)
	at java.base/java.lang.Thread.run(Thread.java:834)
16:48:11.390 [typedb-service::0] ERROR com.vaticle.typedb.core.server.TransactionService - java.util.NoSuchElementException: No value present
com.vaticle.typedb.core.common.exception.TypeDBException: java.util.NoSuchElementException: No value present
	at com.vaticle.typedb.core.common.exception.TypeDBException.of(TypeDBException.java:58)
	at com.vaticle.typedb.core.concurrent.producer.ProducerIterator.hasNext(ProducerIterator.java:100)
	at com.vaticle.typedb.core.common.iterator.ErrorHandledIterator.hasNext(ErrorHandledIterator.java:38)
	at com.vaticle.typedb.core.server.TransactionService$ResponseStream.lambda$streamResParts$0(TransactionService.java:335)
	at com.vaticle.typedb.core.server.TransactionService$ResponseStream.streamResPartsWhile(TransactionService.java:347)
	at com.vaticle.typedb.core.server.TransactionService$ResponseStream.streamResParts(TransactionService.java:335)
	at com.vaticle.typedb.core.server.TransactionService.stream(TransactionService.java:258)
	at com.vaticle.typedb.core.server.TransactionService.stream(TransactionService.java:248)
	at com.vaticle.typedb.core.server.query.QueryService.match(QueryService.java:132)
	at com.vaticle.typedb.core.server.query.QueryService.execute(QueryService.java:84)
	at com.vaticle.typedb.core.server.TransactionService.executeRequest(TransactionService.java:170)
	at com.vaticle.typedb.core.server.TransactionService.execute(TransactionService.java:146)
	at com.vaticle.typedb.core.server.TransactionService.onNext(TransactionService.java:122)
	at com.vaticle.typedb.core.server.TransactionService.onNext(TransactionService.java:79)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:318)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:301)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at com.vaticle.typedb.core.logic.resolvable.Concludable$Relation.unificationSatisfiable(Concludable.java:434)
	at com.vaticle.typedb.core.logic.resolvable.Concludable$Relation.lambda$matchRolePlayers$5(Concludable.java:398)
	at com.vaticle.typedb.core.common.iterator.FilteredIterator.fetchAndCheck(FilteredIterator.java:41)
	at com.vaticle.typedb.core.common.iterator.FilteredIterator.hasNext(FilteredIterator.java:37)
	at com.vaticle.typedb.core.common.iterator.MappedIterator.hasNext(MappedIterator.java:35)
	at com.vaticle.typedb.core.common.iterator.FlatMappedIterator.fetchAndCheck(FlatMappedIterator.java:52)
	at com.vaticle.typedb.core.common.iterator.FlatMappedIterator.hasNext(FlatMappedIterator.java:48)
	at com.vaticle.typedb.core.common.iterator.FlatMappedIterator.fetchAndCheck(FlatMappedIterator.java:52)
	at com.vaticle.typedb.core.common.iterator.FlatMappedIterator.hasNext(FlatMappedIterator.java:48)
	at com.vaticle.typedb.core.common.iterator.MappedIterator.hasNext(MappedIterator.java:35)
	at com.vaticle.typedb.core.common.iterator.FunctionalIterator.forEachRemaining(FunctionalIterator.java:104)
	at com.vaticle.typedb.core.logic.resolvable.Concludable$Relation.lambda$applicableRules$12(Concludable.java:450)
	at com.vaticle.typedb.core.common.iterator.FunctionalIterator.forEachRemaining(FunctionalIterator.java:105)
	at com.vaticle.typedb.core.logic.resolvable.Concludable$Relation.lambda$applicableRules$13(Concludable.java:449)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.vaticle.typedb.core.logic.resolvable.Concludable$Relation.applicableRules(Concludable.java:448)
	at com.vaticle.typedb.core.logic.resolvable.Concludable.getApplicableRules(Concludable.java:112)
	at com.vaticle.typedb.core.reasoner.controller.RootConjunctionController.lambda$concludablesTriggeringRules$1(RootConjunctionController.java:70)
	at com.vaticle.typedb.core.common.iterator.FilteredIterator.fetchAndCheck(FilteredIterator.java:41)
	at com.vaticle.typedb.core.common.iterator.FilteredIterator.hasNext(FilteredIterator.java:37)
	at com.vaticle.typedb.core.common.iterator.FunctionalIterator.forEachRemaining(FunctionalIterator.java:104)
	at com.vaticle.typedb.core.common.iterator.AbstractFunctionalIterator.toSet(AbstractFunctionalIterator.java:198)
	at com.vaticle.typedb.core.reasoner.controller.RootConjunctionController.concludablesTriggeringRules(RootConjunctionController.java:71)
	at com.vaticle.typedb.core.reasoner.controller.ConjunctionController.setUpUpstreamControllers(ConjunctionController.java:88)
	at com.vaticle.typedb.core.reasoner.controller.RootConjunctionController.initialise(RootConjunctionController.java:55)
	at com.vaticle.typedb.core.reasoner.controller.ControllerRegistry.lambda$createRootController$6(ControllerRegistry.java:131)
	at com.vaticle.typedb.core.concurrent.actor.Actor$Driver.lambda$execute$0(Actor.java:80)
	at com.vaticle.typedb.core.concurrent.actor.ActorExecutor$Task.run(ActorExecutor.java:127)
	at com.vaticle.typedb.core.concurrent.actor.ActorExecutor.run(ActorExecutor.java:71)
	... 1 common frames omitted

```
[robotics.txt](https://github.com/vaticle/typedb/files/8863253/robotics.txt)
[data.txt](https://github.com/vaticle/typedb/files/8863257/data.txt)

**Comment by krishnangovindraj** [comment]
Addressed by: https://github.com/vaticle/typeql/pull/227 , making the schema illegal.
The reasoner cannot presently handle inferred roleTypes, though this may be a good enough motivating use-case. 
A new issue has been created here: https://github.com/vaticle/typedb/issues/6697
