### ISSUE TITLE
Hitting OOM issues while delete write transacton

### ISSUE THREAD

**Issue by qqliang** [vaticle/typedb#6668]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

when i use write transaction to delete an entity with 2.5 million data, it encounters a OOM error.

## Environment

1. OS (where TypeDB server runs):  Ubuntu 16.4
2. TypeDB version (and platform): TypeDB 2.11.1
3. TypeDB client: client-python & console 
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. tql: match $t isa comment; delete $t isa comment;
2. comment is a entity with 2.5 million data

## Expected Output

success

## Actual Output

java heap space.
![image](https://user-images.githubusercontent.com/23022359/197329618-ba5b50af-6d1e-42e0-87f8-ce24aee99191.png)

**server log as follows**:

03:59:10.497 [typedb-service::0] ERROR com.vaticle.typedb.core.server.TransactionService - Java heap space
java.lang.OutOfMemoryError: Java heap space
        at com.vaticle.typedb.core.common.iterator.sorted.MergeMappedIterator.<init>(MergeMappedIterator.java:53)
        at com.vaticle.typedb.core.common.iterator.sorted.MergeMappedIterator$Forwardable.<init>(MergeMappedIterator.java:149)
        at com.vaticle.typedb.core.common.iterator.AbstractFunctionalIterator.mergeMap(AbstractFunctionalIterator.java:72)
        at com.vaticle.typedb.core.graph.adjacency.impl.ThingAdjacencyImpl$Write.iterateBufferedViews(ThingAdjacencyImpl.java:242)
        at com.vaticle.typedb.core.graph.adjacency.impl.ThingAdjacencyImpl$Write$Persisted.iterateEdges(ThingAdjacencyImpl.java:464)
        at com.vaticle.typedb.core.graph.adjacency.impl.ThingAdjacencyImpl$Write$Persisted.delete(ThingAdjacencyImpl.java:500)
        at com.vaticle.typedb.core.graph.adjacency.impl.ThingAdjacencyImpl$Write$$Lambda$617/0x0000000800f4c140.accept(Unknown Source)
        at com.vaticle.typedb.core.common.iterator.FunctionalIterator.forEachRemaining(FunctionalIterator.java:105)
        at com.vaticle.typedb.core.graph.adjacency.impl.ThingAdjacencyImpl$Write.deleteAll(ThingAdjacencyImpl.java:362)
        at com.vaticle.typedb.core.graph.vertex.impl.ThingVertexImpl$Write.deleteEdges(ThingVertexImpl.java:205)
        at com.vaticle.typedb.core.graph.vertex.impl.ThingVertexImpl$Write$Persisted.delete(ThingVertexImpl.java:317)
        at com.vaticle.typedb.core.concept.thing.impl.ThingImpl.delete(ThingImpl.java:234)
        at com.vaticle.typedb.core.query.Deleter$Operation.deleteIsa(Deleter.java:183)
        at com.vaticle.typedb.core.query.Deleter$Operation$$Lambda$602/0x0000000800f474c8.accept(Unknown Source)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
        at com.vaticle.typedb.core.query.Deleter$Operation.execute(Deleter.java:133)
        at com.vaticle.typedb.core.query.Deleter.lambda$execute$0(Deleter.java:112)
        at com.vaticle.typedb.core.query.Deleter$$Lambda$600/0x0000000800f46e88.accept(Unknown Source)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at com.vaticle.typedb.core.query.Deleter.execute(Deleter.java:112)
        at com.vaticle.typedb.core.query.QueryManager.delete(QueryManager.java:140)
        at com.vaticle.typedb.core.server.query.QueryService.delete(QueryService.java:165)
        at com.vaticle.typedb.core.server.query.QueryService.execute(QueryService.java:99)
        at com.vaticle.typedb.core.server.TransactionService.executeRequest(TransactionService.java:170)
        at com.vaticle.typedb.core.server.TransactionService.execute(TransactionService.java:146)
        at com.vaticle.typedb.core.server.TransactionService.onNext(TransactionService.java:122)
        at com.vaticle.typedb.core.server.TransactionService.onNext(TransactionService.java:79)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:318)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:301)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834)
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by flyingsilverfin** [comment]
Hi - yes this is a known issue... one way to solve this would be to run `match $t isa comment; limit 1000; delete $t isa comment;` and commit, and repeat this until nothing is deleted :) You'd have to check in between with `match $t isa comment; limit 1;` to see if there are any left before doing the delete... Let us know if that works!

**Comment by qqliang** [comment]
> Hi - yes this is a known issue... one way to solve this would be to run `match $t isa comment; limit 1000; delete $t isa comment;` and commit, and repeat this until nothing is deleted :) You'd have to check in between with `match $t isa comment; limit 1;` to see if there are any left before doing the delete... Let us know if that works!

thanks for your reply, I will use this method to delete data.
